jwt:
 secret: zeta
 except: >
  /authenticate
  /api/**
 expire:
  hour: 24
 
server:
 port: 8889

spring:
  profiles:
   active: local

---

spring:
  profiles: local
  datasource:
   username: glyde
   password: glyde1234!
   driver-class-name: org.postgresql.Driver
   url: jdbc:postgresql://localhost:15432/glyde01?ssl=false 